import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import { getFirestore, collection, addDoc, deleteDoc, doc, onSnapshot, orderBy, query, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import { app } from "./firebase-config.js";

const auth=getAuth(app),db=getFirestore(app),form=document.querySelector('#room-post-form'),feed=document.querySelector('#room-feed'),status=document.querySelector('#room-post-status'),filterButtons=document.querySelectorAll('[data-room-filter]');
let currentUser=null,posts=[],activeFilter='all';
const replyState=new Map(),replyUnsubs=new Map(),linkMeta=new Map();
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const setStatus=(m,t='')=>{if(status){status.textContent=m;status.dataset.type=t;}};
const fmt=t=>t?.toDate?t.toDate().toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'}):'Just now';
const preview=t=>t.length>90?`${t.slice(0,90).trim()}…`:t;
const urlRe=/https?:\/\/[^\s<>"']+/gi;
function cleanUrl(raw){try{const u=new URL(raw.replace(/[),.!?;:]+$/,''));return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function urlsIn(text=''){return [...new Set((text.match(urlRe)||[]).map(cleanUrl).filter(Boolean))].slice(0,3);}
function linkify(text=''){let out='',last=0;for(const m of text.matchAll(urlRe)){out+=esc(text.slice(last,m.index));const url=cleanUrl(m[0]);if(url){const safe=esc(url);out+=`<a class="room-inline-link" href="${safe}" target="_blank" rel="noopener noreferrer nofollow">${esc(m[0])}</a>`;}else out+=esc(m[0]);last=m.index+m[0].length;}return (out+esc(text.slice(last))).replace(/\n/g,'<br>');}
function fallbackMeta(url){const u=new URL(url);return {url,title:u.hostname.replace(/^www\./,''),description:'Open this link shared by a V2 Room member.',domain:u.hostname.replace(/^www\./,''),rich:false};}
async function fetchMeta(url){if(linkMeta.has(url))return;linkMeta.set(url,fallbackMeta(url));try{const u=new URL(url);if(u.origin!==location.origin)return;const r=await fetch(url,{headers:{Accept:'text/html'},credentials:'omit'});if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))return;const html=await r.text(),d=new DOMParser().parseFromString(html.slice(0,250000),'text/html');const title=(d.querySelector('meta[property="og:title"]')?.content||d.title||u.hostname).trim().slice(0,140),description=(d.querySelector('meta[property="og:description"]')?.content||d.querySelector('meta[name="description"]')?.content||'').trim().slice(0,240);linkMeta.set(url,{url,title,description:description||'Open this page shared by a V2 Room member.',domain:u.hostname.replace(/^www\./,''),rich:true});renderPosts();}catch(e){console.debug('Link preview fallback:',e);}}
function linkCards(text=''){const urls=urlsIn(text);urls.forEach(fetchMeta);return urls.length?`<div class="room-link-previews">${urls.map(url=>{const m=linkMeta.get(url)||fallbackMeta(url);return `<a class="room-link-card${m.rich?' is-rich':''}" href="${esc(url)}" target="_blank" rel="noopener noreferrer nofollow"><span class="room-link-domain">${esc(m.domain)}</span><strong>${esc(m.title)}</strong><span>${esc(m.description)}</span><small>Open link ↗</small></a>`;}).join('')}</div>`:'';}

function ensureReplies(postId){if(replyUnsubs.has(postId))return;const q=query(collection(db,'communityPosts',postId,'replies'),orderBy('createdAt','asc'));replyUnsubs.set(postId,onSnapshot(q,s=>{replyState.set(postId,s.docs.map(d=>({id:d.id,...d.data()})));renderPosts();},e=>console.error('Replies:',e)));}
function replyMarkup(post){const all=replyState.get(post.id)||[],roots=all.filter(r=>!r.parentReplyId);return `<section class="room-replies"><div class="room-reply-head"><strong>${roots.length} ${roots.length===1?'reply':'replies'}</strong><button type="button" data-start-reply="${post.id}">Reply</button></div><form class="room-reply-form" data-reply-form="${post.id}" hidden><textarea maxlength="1000" rows="3" required placeholder="Write your reply…"></textarea><div><button class="btn btn-primary" type="submit">Post reply</button><button type="button" data-cancel-reply="${post.id}">Cancel</button></div></form><div class="room-reply-list">${roots.map(r=>{const children=all.filter(x=>x.parentReplyId===r.id),latest=children.at(-1);return `<article class="room-reply"><div class="room-reply-meta"><strong>${esc(r.authorName||'V2 Member')}</strong><time>${fmt(r.createdAt)}</time></div><p>${linkify(r.body)}</p>${linkCards(r.body)}<div class="room-reply-actions"><button type="button" data-start-response="${post.id}|${r.id}">Reply</button>${r.authorUid===currentUser?.uid?`<button type="button" data-delete-reply="${post.id}|${r.id}">Delete</button>`:''}</div>${children.length?`<button class="room-thread-toggle" type="button" data-toggle-thread="${post.id}|${r.id}">View ${children.length} ${children.length===1?'response':'responses'}</button><p class="room-thread-preview"><strong>Latest: ${esc(latest.authorName||'V2 Member')}</strong> — ${esc(preview(latest.body))}</p>`:''}<form class="room-response-form" data-response-form="${post.id}|${r.id}" hidden><textarea maxlength="1000" rows="2" required placeholder="Respond to this reply…"></textarea><div><button class="btn btn-primary" type="submit">Post response</button><button type="button" data-cancel-response="${post.id}|${r.id}">Cancel</button></div></form><div class="room-thread" data-thread="${post.id}|${r.id}" hidden>${children.map(c=>`<article class="room-response"><div class="room-reply-meta"><strong>${esc(c.authorName||'V2 Member')}</strong><time>${fmt(c.createdAt)}</time></div><p>${linkify(c.body)}</p>${linkCards(c.body)}${c.authorUid===currentUser?.uid?`<button type="button" data-delete-reply="${post.id}|${c.id}">Delete</button>`:''}</article>`).join('')}</div></article>`}).join('')}</div></section>`;}
function renderPosts(){if(!feed)return;const visible=activeFilter==='all'?posts:posts.filter(p=>p.type===activeFilter);if(!visible.length){feed.innerHTML='<div class="room-empty">No posts here yet. Start the conversation.</div>';return;}visible.filter(p=>p.type==='question').forEach(p=>ensureReplies(p.id));feed.innerHTML=visible.map(p=>{const mine=currentUser&&p.authorUid===currentUser.uid,label=p.type==='question'?'Ask the Room':'Noticeboard';return `<article class="room-post"><div class="room-post-meta"><span>${label}</span><time>${fmt(p.createdAt)}</time></div><h3>${esc(p.title)}</h3><p>${linkify(p.body)}</p>${linkCards(p.body)}<div class="room-post-author"><strong>${esc(p.authorName||'V2 Member')}</strong>${mine?`<button type="button" data-delete-post="${p.id}">Delete</button>`:''}</div>${p.type==='question'?replyMarkup(p):''}</article>`}).join('');bindActions();}
function toggleForm(selector,key,show=true){const el=feed.querySelector(`${selector}[data-${selector.includes('response')?'response-form':'reply-form'}="${CSS.escape(key)}"]`);if(el)el.hidden=!show;}
async function addReply(postId,body,parentReplyId=null){await addDoc(collection(db,'communityPosts',postId,'replies'),{body:body.slice(0,1000),authorUid:currentUser.uid,authorName:currentUser.displayName||'V2 Member',parentReplyId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});}
function bindActions(){feed.querySelectorAll('[data-delete-post]').forEach(b=>b.onclick=async()=>{if(currentUser&&confirm('Delete this post?'))await deleteDoc(doc(db,'communityPosts',b.dataset.deletePost));});feed.querySelectorAll('[data-start-reply]').forEach(b=>b.onclick=()=>toggleForm('.room-reply-form',b.dataset.startReply));feed.querySelectorAll('[data-cancel-reply]').forEach(b=>b.onclick=()=>toggleForm('.room-reply-form',b.dataset.cancelReply,false));feed.querySelectorAll('[data-start-response]').forEach(b=>b.onclick=()=>toggleForm('.room-response-form',b.dataset.startResponse));feed.querySelectorAll('[data-cancel-response]').forEach(b=>b.onclick=()=>toggleForm('.room-response-form',b.dataset.cancelResponse,false));feed.querySelectorAll('[data-toggle-thread]').forEach(b=>b.onclick=()=>{const k=b.dataset.toggleThread,t=feed.querySelector(`[data-thread="${CSS.escape(k)}"]`),p=b.parentElement.querySelector('.room-thread-preview');t.hidden=!t.hidden;if(p)p.hidden=!t.hidden;b.textContent=t.hidden?b.textContent.replace('Hide','View'):b.textContent.replace('View','Hide');});feed.querySelectorAll('[data-delete-reply]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this reply?'))return;const [p,r]=b.dataset.deleteReply.split('|');await deleteDoc(doc(db,'communityPosts',p,'replies',r));});feed.querySelectorAll('[data-reply-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const body=f.querySelector('textarea').value.trim();if(body.length<2)return;const btn=f.querySelector('[type=submit]');btn.disabled=true;try{await addReply(f.dataset.replyForm,body);f.reset();f.hidden=true;}finally{btn.disabled=false;}});feed.querySelectorAll('[data-response-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const body=f.querySelector('textarea').value.trim();if(body.length<2)return;const [p,parent]=f.dataset.responseForm.split('|'),btn=f.querySelector('[type=submit]');btn.disabled=true;try{await addReply(p,body,parent);f.reset();f.hidden=true;}finally{btn.disabled=false;}});}
filterButtons.forEach(b=>b.addEventListener('click',()=>{activeFilter=b.dataset.roomFilter;filterButtons.forEach(x=>x.classList.toggle('active',x===b));renderPosts();}));
onAuthStateChanged(auth,user=>{currentUser=user;if(!user)return;onSnapshot(query(collection(db,'communityPosts'),orderBy('createdAt','desc')),s=>{posts=s.docs.map(d=>({id:d.id,...d.data()}));renderPosts();},e=>{console.error(e);feed.innerHTML='<div class="room-empty">The community feed could not be loaded.</div>';});});
form?.addEventListener('submit',async e=>{e.preventDefault();if(!currentUser)return;const type=form.elements.type.value,title=form.elements.title.value.trim(),body=form.elements.body.value.trim();if(!['notice','question'].includes(type)||title.length<3||body.length<5){setStatus('Add a title and enough detail for other members to respond.','error');return;}const submit=form.querySelector('[type=submit]');submit.disabled=true;setStatus('Posting…');try{await addDoc(collection(db,'communityPosts'),{type,title:title.slice(0,120),body:body.slice(0,2000),authorUid:currentUser.uid,authorName:currentUser.displayName||'V2 Member',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});form.reset();setStatus('Posted to The V2 Room.','success');}catch(err){console.error(err);setStatus('Unable to publish the post.','error');}finally{submit.disabled=false;}});